<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsp</string>
		<string>jspf</string>
		<string>tag</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JSTL</string>
	<key>patterns</key>
	<array>
		<!-- Targeting all of the JSP tags/attributes separately; This should let us color them however we want -->
		<dict>
			<!-- Start by targeting all alphanumeric tags with colons in them -->
			<key>begin</key>
			<string>(&lt;/?)([a-zA-Z0-9]++(:)[a-zA-Z0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.dsp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.dsp</string>
				</dict>
			</dict>
			<!-- then target the closers -->
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.dsp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.dsp</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<!-- target the substrings separately -->
				<dict>
					<key>match</key>
					<string>([""'])(?:(?=(\\?))\2.)*?\1</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<!-- target the equals separately -->
				<dict>
					<key>match</key>
					<string>([=])</string>
					<key>name</key>
					<string>constant.other.color</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.jsp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.jsp.jstl</string>
	<key>uuid</key>
	<string>1526c0f7-23e7-4462-8906-9420bf2f80c6</string>
</dict>
</plist>
