<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsp</string>
		<string>jspf</string>
		<string>tag</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JSTL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expression-language</string>
		</dict>
		<!-- Targeting all of the JSP tags/attributes separately; This should let us color them however we want -->
		<dict>
			<!-- Start by targeting all alphanumeric tags with colons in them -->
			<key>begin</key>
			<string>(&lt;/?)(([a-zA-Z0-9\-]++)(:)([a-zA-Z0-9\-]+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html.jsp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html.jsp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.html.jsp</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.html.jsp</string>
				</dict>
			</dict>
			<!-- then target the closers -->
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html.jsp</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double-quotes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quotes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<!-- target the equals separately -->
				<dict>
					<key>match</key>
					<string>([=])</string>
					<key>name</key>
					<string>constant.other.color</string>
				</dict>
			</array>
		</dict>
		<!--<dict>
			<key>begin</key>
			<string>(&lt;/?)([a-zA-Z0-9\-]++)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double-quotes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quotes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
			</array>
		</dict>-->
		<dict>
			<key>include</key>
			<string>text.html.jsp</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html.jsp</string>
		</dict>
		<key>single-quotes</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html.jsp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html.jsp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html.jsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-language</string>
				</dict>
			</array>
		</dict>
		<key>double-quotes</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html.jsp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html.jsp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html.jsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-language</string>
				</dict>
			</array>
		</dict>
		<key>expression-language</key>
		<dict>
			<key>begin</key>
			<string>\$\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interpolated.begin.el</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.interpolated.end.el</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.interpolated.el</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#el-source</string>
				</dict>
			</array>
		</dict>
		<key>el-source</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>operators that evaluate to True or False</string>
					<key>match</key>
					<string>\b(and|or|not|empty|\!|\|\||&amp;&amp;)|\?|\:\b</string>
					<key>name</key>
					<string>keyword.operator.logical.el</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=|\beq\b|\bne\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.el</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.jsp.jstl</string>
	<key>uuid</key>
	<string>1526c0f7-23e7-4462-8906-9420bf2f80c6</string>
</dict>
</plist>
